export const FETCH_CREATE_CHAT_REQUEST = "FETCH_CREATE_CHAT_REQUEST";
export const FETCH_CREATE_CHAT_SUCCESS = "FETCH_CREATE_CHAT_SUCCESS";
export const FETCH_CREATE_CHAT_FAILURE = "FETCH_CREATE_CHAT_FAILURE";
